name: 'github actions k3s'
author: 'Dmitry Rozhdestvenskiy <yellowmegaman@gmail.com>'
description: 'run k3s on github actions'
branding:
  icon: 'aperture'
  color: 'yellow'
inputs:
  k3s_tag:
    description: "k3s tag to use"
    required: false
    default: 'v1.29.4+k3s1'
  k3s_arguments:
    description: "k3s arguments"
    required: false
    default: ""
  kubectl_version:
    description: "kubectl version to use"
    required: false
    default: "v1.29.4"
  registries_yaml_path:
    description: "where to look for registries.yaml, relative path"
    required: false
    default: ""
  containerd_toml_path:
    description: "where to look for containerd.toml, relative path"
    required: false
    default: ""
  install_kubectl:
    description: "whenever to copy kubectl to runner workspace"
    required: false
    default: "true"
runs:
  using: 'docker'
  image: 'Dockerfile'
